# -*- coding: utf-8 -*-
"""Analyst Project-Nick

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyMujDRl79W-I2IlW4l-RVFpDc3sKq54

# MACHINE LEARNING Challenge

## Classification with Logistic Regression and Decision Trees

In this assignment, you will work with a real-world credit dataset and build two supervised classification models:

* Logistic Regression
* Decision Tree

Your objective is to:

1. Prepare the dataset appropriately for modeling.
2. Train both models.
3. Evaluate their performance.
4. Compare the results and draw conclusions.

---

# DATASET — CREDIT

## Business Context

You are working as a data analyst for a financial institution. The company wants to improve its credit approval process by better understanding the characteristics associated with credit approval and credit risk.

Using customer demographic, financial, and behavioral information, you must build a model that predicts whether a credit application will be granted.

---

## Target Variable

**Granted**

* 1 → Credit application approved
* 0 → Credit application rejected

This is a binary classification problem.

---
# STEP 1: Data Import & Initial Viewing
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_excel("credit_V2.xlsx")

df.head()

df.info()

df.describe()

"""---
# STEP 2: Data Cleaning & Handling Formatting Inconsistencies

Before encoding or modeling, we must fix inconsistencies found during inspection:
- **`Saving accounts`**: contains `'#'` (invalid) and `'Moderate'` (should be `'moderate'` — case inconsistency)
- **`Purpose`**: contains `'?'` and `'#'` as invalid entries
- **`Employment_Type`**: contains `'#'` as an invalid entry
- **`Education_Level`**: contains `'?'` and `'#'` as invalid entries
- **`Marital_Status`**: contains `'married'` (lowercase) which should be `'Married'`
- **Rows with NaN** in key columns are dropped
- **`Customer_id`** is an identifier and will be dropped before modeling
"""

df["Saving accounts"] = df["Saving accounts"].str.lower()

df = df.replace(['#', '?'], pd.NA)

df["Marital_Status"] = df["Marital_Status"].str.strip().str.capitalize()

df = df.drop(columns=["Customer_id"])

df = df.dropna()
df = df.reset_index(drop=True)

print(f"Dataset shape after cleaning: {df.shape}")
df.head()

"""---
# STEP 3: Outlier Detection

We use the **IQR method** to identify outliers in the numerical columns. Rows with outliers in any numerical column are removed.
"""

numerical_cols = ["Age", "Credit_amount", "Duration", "Debt_to_Income_Ratio", "Credit_Score"]

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outlier_count = df[(df[col] < lower_bound) | (df[col] > upper_bound)].shape[0]
    print(f"{col}: {outlier_count} outliers detected (bounds: [{lower_bound:.2f}, {upper_bound:.2f}])")
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

df = df.reset_index(drop=True)
print(f"\nDataset shape after outlier removal: {df.shape}")

"""---
# STEP 4: Exploratory Visuals

Before modeling, we do a quick check for class imbalance in the target variable and explore relationships.
"""

sns.countplot(data=df, x="Granted")
plt.title("Distribution of Target Variable (Granted)")
plt.show()

sns.scatterplot(data=df, x="Credit_Score", y="Debt_to_Income_Ratio", hue="Granted")
plt.title("Credit Score vs Debt-to-Income Ratio by Granted Status")
plt.show()

"""---
# STEP 5: Categorical Data Encoding

The dataset contains both **nominal** (no order) and **ordinal** (ranked) categorical variables.

**Nominal columns** → One-Hot Encoding:
- `Sex`, `Housing`, `Purpose`, `Employment_Type`, `Marital_Status`

**Ordinal columns** → Manual Mapping (preserving natural order):
- `Saving accounts`: little < moderate < quite rich < rich
- `Education_Level`: Primary < Secondary < Bachelor < Master < PhD
- `Risk_Category`: Low < Medium < High < Very High
"""

nominal_cols = ["Sex", "Housing", "Purpose", "Employment_Type", "Marital_Status"]

encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
encoded_array = encoder.fit_transform(df[nominal_cols])
encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder.get_feature_names_out(nominal_cols),
    index=df.index
)
df = pd.concat([df.drop(columns=nominal_cols), encoded_df], axis=1)

print("One-Hot Encoding applied. New shape:", df.shape)

saving_mapping = {
    "little": 0,
    "moderate": 1,
    "quite rich": 2,
    "rich": 3
}
df["Saving accounts"] = df["Saving accounts"].map(saving_mapping)

education_mapping = {
    "Primary": 0,
    "Secondary": 1,
    "Bachelor": 2,
    "Master": 3,
    "Phd": 4,
    "PhD": 4
}
df["Education_Level"] = df["Education_Level"].map(education_mapping)

risk_mapping = {
    "Low": 0,
    "Medium": 1,
    "High": 2,
    "Very High": 3
}
df["Risk_Category"] = df["Risk_Category"].map(risk_mapping)

print("Ordinal Encoding applied.")
df.head()

"""---
# STEP 6: Data Splitting
"""

X = df.drop(columns=["Granted"])
y = df["Granted"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(f"Training set size: {X_train.shape[0]} rows")
print(f"Testing set size:  {X_test.shape[0]} rows")

"""---
# STEP 7: Model 1 — Decision Tree
"""

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

dt_predictions = dt_model.predict(X_test)

print("Decision Tree trained successfully.")

print("=== Decision Tree: Classification Report ===")
print(classification_report(y_test, dt_predictions))

print("=== Decision Tree: Confusion Matrix ===")
print(confusion_matrix(y_test, dt_predictions))

plt.figure(figsize=(20, 10))
plot_tree(
    dt_model,
    feature_names=X.columns,
    filled=True,
    rounded=True,
    max_depth=3
)
plt.title("Decision Tree (first 3 levels)")
plt.show()

"""---
# STEP 8: Model 2 — Logistic Regression
"""

lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train, y_train)

lr_predictions = lr_model.predict(X_test)

print("Logistic Regression trained successfully.")

print("=== Logistic Regression: Classification Report ===")
print(classification_report(y_test, lr_predictions))

print("=== Logistic Regression: Confusion Matrix ===")
print(confusion_matrix(y_test, lr_predictions))

"""---
# STEP 9: Discussion & Conclusions

## Decision Tree — Rules Discussion

The Decision Tree generates interpretable **if/then rules** based on the most predictive features. Reading the top levels of the tree (visualized above), we can identify which variables drive credit approval decisions the most. Typically, features such as **Credit_Score**, **Risk_Category**, and **Debt_to_Income_Ratio** appear near the root of the tree, indicating they are the strongest predictors of whether credit is granted. Each internal node in the tree represents a split on a feature with a threshold — for example, `Credit_Score <= 620 → likely rejected`. This makes the Decision Tree highly interpretable for business stakeholders.

## Model Comparison

| Metric | Decision Tree | Logistic Regression |
|---|---|---|
| Accuracy | See report above | See report above |
| Precision (class 0) | See report above | See report above |
| Recall (class 0) | See report above | See report above |
| Interpretability | High (tree rules) | Moderate (coefficients) |

## Conclusion

Both models are suitable for this binary classification problem. **Logistic Regression** tends to generalize better on balanced datasets and is less prone to overfitting, making it a strong baseline. The **Decision Tree**, while potentially more prone to overfitting if not pruned, offers clear interpretability — the rules it generates can be directly communicated to credit officers.

Based on the classification reports:
- If **overall accuracy and F1-score** are higher for Logistic Regression, it is the better model for deployment.
- If the business needs **explainable rules** (e.g., for regulatory compliance), the Decision Tree is preferred despite potentially lower accuracy.

Given the nature of credit approval — where explainability matters — **the Decision Tree provides additional business value**, even if both models achieve comparable performance.
"""